[package]
name = "gl-test"
version = "0.0.1"


[dependencies]
glutin = { git = "https://github.com/doukutsu-rs/glutin.git", rev = "2dd95f042e6e090d36f577cbea125560dd99bd27", optional = false, default_features = false, features = ["x11"] }
gl = {}
log = {}






